- Add mutex mgr and atomic op mgrs for notheads case. - Add atomic op mgr for Mac OS case.
git-svn-id: https://svn.apache.org/repos/asf/xerces/c/branches/jberry@178660 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/3.0-unstable/configure b/3.0-unstable/configure
--- a/3.0-unstable/configure
+++ b/3.0-unstable/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LN_S EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBOBJS CURL_PREFIX XERCES_USE_NETACCESSOR_CURL_TRUE XERCES_USE_NETACCESSOR_CURL_FALSE XERCES_USE_NETACCESSOR_CFURL_TRUE XERCES_USE_NETACCESSOR_CFURL_FALSE XERCES_USE_NETACCESSOR_WINSOCK_TRUE XERCES_USE_NETACCESSOR_WINSOCK_FALSE XERCES_USE_NETACCESSOR_SOCKET_TRUE XERCES_USE_NETACCESSOR_SOCKET_FALSE XERCES_USE_NETACCESSOR_LIBWWW_TRUE XERCES_USE_NETACCESSOR_LIBWWW_FALSE ICU_PREFIX XERCES_USE_TRANSCODER_ICU_TRUE XERCES_USE_TRANSCODER_ICU_FALSE XERCES_USE_TRANSCODER_MACOSUNICODECONVERTER_TRUE XERCES_USE_TRANSCODER_MACOSUNICODECONVERTER_FALSE XERCES_USE_MSGLOADER_INMEMORY_TRUE XERCES_USE_MSGLOADER_INMEMORY_FALSE XERCES_USE_FILEMGR_POSIX_TRUE XERCES_USE_FILEMGR_POSIX_FALSE XERCES_USE_MUTEXMGR_POSIX_TRUE XERCES_USE_MUTEXMGR_POSIX_FALSE XERCES_USE_ATOMICOPMGR_POSIX_TRUE XERCES_USE_ATOMICOPMGR_POSIX_FALSE LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LN_S EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBOBJS CURL_PREFIX XERCES_USE_NETACCESSOR_CURL_TRUE XERCES_USE_NETACCESSOR_CURL_FALSE XERCES_USE_NETACCESSOR_CFURL_TRUE XERCES_USE_NETACCESSOR_CFURL_FALSE XERCES_USE_NETACCESSOR_WINSOCK_TRUE XERCES_USE_NETACCESSOR_WINSOCK_FALSE XERCES_USE_NETACCESSOR_SOCKET_TRUE XERCES_USE_NETACCESSOR_SOCKET_FALSE XERCES_USE_NETACCESSOR_LIBWWW_TRUE XERCES_USE_NETACCESSOR_LIBWWW_FALSE ICU_PREFIX XERCES_USE_TRANSCODER_ICU_TRUE XERCES_USE_TRANSCODER_ICU_FALSE XERCES_USE_TRANSCODER_MACOSUNICODECONVERTER_TRUE XERCES_USE_TRANSCODER_MACOSUNICODECONVERTER_FALSE XERCES_USE_MSGLOADER_INMEMORY_TRUE XERCES_USE_MSGLOADER_INMEMORY_FALSE XERCES_USE_FILEMGR_POSIX_TRUE XERCES_USE_FILEMGR_POSIX_FALSE XERCES_USE_MUTEXMGR_NOTHREAD_TRUE XERCES_USE_MUTEXMGR_NOTHREAD_FALSE XERCES_USE_MUTEXMGR_POSIX_TRUE XERCES_USE_MUTEXMGR_POSIX_FALSE XERCES_USE_ATOMICOPMGR_NOTHREAD_TRUE XERCES_USE_ATOMICOPMGR_NOTHREAD_FALSE XERCES_USE_ATOMICOPMGR_POSIX_TRUE XERCES_USE_ATOMICOPMGR_POSIX_FALSE XERCES_USE_ATOMICOPMGR_MACOS_TRUE XERCES_USE_ATOMICOPMGR_MACOS_FALSE LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1053,6 +1053,7 @@ Optional Features:
                           support
   --enable-msgloader-inmemory
                           Enable InMemory MsgLoader support
+  --enable-threads        Enable Threading (default)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -4267,7 +4268,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4270 "configure"' > conftest.$ac_ext
+  echo '#line 4271 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5382,7 +5383,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5385:" \
+echo "$as_me:5386:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6451,11 +6452,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6454: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6455: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6458: \$? = $ac_status" >&5
+   echo "$as_me:6459: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6706,11 +6707,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6709: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6710: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6713: \$? = $ac_status" >&5
+   echo "$as_me:6714: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6766,11 +6767,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6769: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6770: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6773: \$? = $ac_status" >&5
+   echo "$as_me:6774: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8966,7 +8967,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8969 "configure"
+#line 8970 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9064,7 +9065,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9067 "configure"
+#line 9068 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11284,11 +11285,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11287: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11288: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11291: \$? = $ac_status" >&5
+   echo "$as_me:11292: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11344,11 +11345,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11347: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11348: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11351: \$? = $ac_status" >&5
+   echo "$as_me:11352: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12707,7 +12708,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12710 "configure"
+#line 12711 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12805,7 +12806,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12808 "configure"
+#line 12809 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13660,11 +13661,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13663: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13664: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13667: \$? = $ac_status" >&5
+   echo "$as_me:13668: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13720,11 +13721,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13723: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13724: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13727: \$? = $ac_status" >&5
+   echo "$as_me:13728: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15776,11 +15777,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15779: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15780: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15783: \$? = $ac_status" >&5
+   echo "$as_me:15784: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16031,11 +16032,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16034: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16035: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16038: \$? = $ac_status" >&5
+   echo "$as_me:16039: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16091,11 +16092,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16094: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16095: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16098: \$? = $ac_status" >&5
+   echo "$as_me:16099: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18291,7 +18292,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18294 "configure"
+#line 18295 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18389,7 +18390,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18392 "configure"
+#line 18393 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -24321,17 +24322,57 @@ fi
 
 
 
+	# Check whether --enable-threads or --disable-threads was given.
+if test "${enable_threads+set}" = set; then
+  enableval="$enable_threads"
+  if test x"$enableval" = xno; then
+  xerces_cv_no_threads=yes
+fi
+
+else
+  xerces_cv_no_threads=no
+fi;
+	if test x$xerces_cv_no_threads = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define NO_THREADS 1
+_ACEOF
+
+fi
+
+
+
+
+
 
 	echo "$as_me:$LINENO: checking for which Mutex Manager to use" >&5
 echo $ECHO_N "checking for which Mutex Manager to use... $ECHO_C" >&6
 	mgr=
 
+	# If no threads is specified, use the NoThread Mutex Mgr
+	if test x$xerces_cv_no_threads = xyes; then
+
+			mgr=NoThreads
+
+cat >>confdefs.h <<\_ACEOF
+#define XERCES_USE_MUTEXMGR_NOTHREAD 1
+_ACEOF
+
+
+fi
+
+
 	# Platform specific checks
-	case $host_os in
-	windows* | cygwin*)
-		#mgr=Windows
-		;;
-	esac
+	if test -z "$mgr"; then
+
+			case $host_os in
+			windows* | cygwin*)
+				#mgr=Windows
+				;;
+			esac
+
+fi
+
 
 	# Fall back to using posix mutex
 	if test -z "$mgr"; then
@@ -24352,6 +24393,16 @@ echo "${ECHO_T}$mgr" >&6
 	# Note that these macros can't be executed conditionally, which is why they're here, not above.
 
 
+if test x"$mgr" = xNoThreads; then
+  XERCES_USE_MUTEXMGR_NOTHREAD_TRUE=
+  XERCES_USE_MUTEXMGR_NOTHREAD_FALSE='#'
+else
+  XERCES_USE_MUTEXMGR_NOTHREAD_TRUE='#'
+  XERCES_USE_MUTEXMGR_NOTHREAD_FALSE=
+fi
+
+
+
 if test x"$mgr" = xPOSIX; then
   XERCES_USE_MUTEXMGR_POSIX_TRUE=
   XERCES_USE_MUTEXMGR_POSIX_FALSE='#'
@@ -24365,20 +24416,54 @@ fi
 
 
 
+
 	echo "$as_me:$LINENO: checking for which AtomicOp Manager to use" >&5
 echo $ECHO_N "checking for which AtomicOp Manager to use... $ECHO_C" >&6
 	mgr=
 
+	# If no threads is specified, use the NoThread Atomic Op Mgr
+	if test x$xerces_cv_no_threads = xyes; then
+
+			mgr=NoThreads
+
+cat >>confdefs.h <<\_ACEOF
+#define XERCES_USE_ATOMICOPMGR_NOTHREAD 1
+_ACEOF
+
+
+fi
+
+
 	# Platform specific checks
-	case $host_os in
-	windows* | cygwin*)
-		#mgr=Windows
-		;;
-	esac
+	if test -z "$mgr"; then
+
+			case $host_os in
+			windows* | cygwin*)
+				#mgr=Windows
+				;;
+			darwin*)
+				# On MacOS, use the built-in AtomicOp primitives
+				if test x$ac_cv_header_CoreServices_CoreServices_h = xyes; then
+
+						mgr=MacOS
+
+cat >>confdefs.h <<\_ACEOF
+#define XERCES_USE_ATOMICOPMGR_MACOS 1
+_ACEOF
+
+
+fi
+
+				;;
+			esac
+
+fi
+
 
 	# Fall back to using posix mutex
 	if test -z "$mgr"; then
-  mgr=POSIX;
+
+			mgr=POSIX;
 
 cat >>confdefs.h <<\_ACEOF
 #define XERCES_USE_ATOMICOPMGR_POSIX 1
@@ -24395,12 +24480,32 @@ echo "${ECHO_T}$mgr" >&6
 	# Note that these macros can't be executed conditionally, which is why they're here, not above.
 
 
+if test x"$mgr" = xNoThreads; then
+  XERCES_USE_ATOMICOPMGR_NOTHREAD_TRUE=
+  XERCES_USE_ATOMICOPMGR_NOTHREAD_FALSE='#'
+else
+  XERCES_USE_ATOMICOPMGR_NOTHREAD_TRUE='#'
+  XERCES_USE_ATOMICOPMGR_NOTHREAD_FALSE=
+fi
+
+
+
 if test x"$mgr" = xPOSIX; then
   XERCES_USE_ATOMICOPMGR_POSIX_TRUE=
   XERCES_USE_ATOMICOPMGR_POSIX_FALSE='#'
 else
   XERCES_USE_ATOMICOPMGR_POSIX_TRUE='#'
   XERCES_USE_ATOMICOPMGR_POSIX_FALSE=
+fi
+
+
+
+if test x"$mgr" = xMacOS; then
+  XERCES_USE_ATOMICOPMGR_MACOS_TRUE=
+  XERCES_USE_ATOMICOPMGR_MACOS_FALSE='#'
+else
+  XERCES_USE_ATOMICOPMGR_MACOS_TRUE='#'
+  XERCES_USE_ATOMICOPMGR_MACOS_FALSE=
 fi
 
 
@@ -24724,6 +24829,13 @@ echo "$as_me: error: conditional \"XERCES_USE_FILEMGR_POSIX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${XERCES_USE_MUTEXMGR_NOTHREAD_TRUE}" && test -z "${XERCES_USE_MUTEXMGR_NOTHREAD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"XERCES_USE_MUTEXMGR_NOTHREAD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"XERCES_USE_MUTEXMGR_NOTHREAD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${XERCES_USE_MUTEXMGR_POSIX_TRUE}" && test -z "${XERCES_USE_MUTEXMGR_POSIX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"XERCES_USE_MUTEXMGR_POSIX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -24731,10 +24843,24 @@ echo "$as_me: error: conditional \"XERCES_USE_MUTEXMGR_POSIX\" was never defined
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${XERCES_USE_ATOMICOPMGR_NOTHREAD_TRUE}" && test -z "${XERCES_USE_ATOMICOPMGR_NOTHREAD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"XERCES_USE_ATOMICOPMGR_NOTHREAD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"XERCES_USE_ATOMICOPMGR_NOTHREAD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${XERCES_USE_ATOMICOPMGR_POSIX_TRUE}" && test -z "${XERCES_USE_ATOMICOPMGR_POSIX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"XERCES_USE_ATOMICOPMGR_POSIX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"XERCES_USE_ATOMICOPMGR_POSIX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${XERCES_USE_ATOMICOPMGR_MACOS_TRUE}" && test -z "${XERCES_USE_ATOMICOPMGR_MACOS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"XERCES_USE_ATOMICOPMGR_MACOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"XERCES_USE_ATOMICOPMGR_MACOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -25364,10 +25490,16 @@ s,@XERCES_USE_MSGLOADER_INMEMORY_TRUE@,$XERCES_USE_MSGLOADER_INMEMORY_TRUE,;t t
 s,@XERCES_USE_MSGLOADER_INMEMORY_FALSE@,$XERCES_USE_MSGLOADER_INMEMORY_FALSE,;t t
 s,@XERCES_USE_FILEMGR_POSIX_TRUE@,$XERCES_USE_FILEMGR_POSIX_TRUE,;t t
 s,@XERCES_USE_FILEMGR_POSIX_FALSE@,$XERCES_USE_FILEMGR_POSIX_FALSE,;t t
+s,@XERCES_USE_MUTEXMGR_NOTHREAD_TRUE@,$XERCES_USE_MUTEXMGR_NOTHREAD_TRUE,;t t
+s,@XERCES_USE_MUTEXMGR_NOTHREAD_FALSE@,$XERCES_USE_MUTEXMGR_NOTHREAD_FALSE,;t t
 s,@XERCES_USE_MUTEXMGR_POSIX_TRUE@,$XERCES_USE_MUTEXMGR_POSIX_TRUE,;t t
 s,@XERCES_USE_MUTEXMGR_POSIX_FALSE@,$XERCES_USE_MUTEXMGR_POSIX_FALSE,;t t
+s,@XERCES_USE_ATOMICOPMGR_NOTHREAD_TRUE@,$XERCES_USE_ATOMICOPMGR_NOTHREAD_TRUE,;t t
+s,@XERCES_USE_ATOMICOPMGR_NOTHREAD_FALSE@,$XERCES_USE_ATOMICOPMGR_NOTHREAD_FALSE,;t t
 s,@XERCES_USE_ATOMICOPMGR_POSIX_TRUE@,$XERCES_USE_ATOMICOPMGR_POSIX_TRUE,;t t
 s,@XERCES_USE_ATOMICOPMGR_POSIX_FALSE@,$XERCES_USE_ATOMICOPMGR_POSIX_FALSE,;t t
+s,@XERCES_USE_ATOMICOPMGR_MACOS_TRUE@,$XERCES_USE_ATOMICOPMGR_MACOS_TRUE,;t t
+s,@XERCES_USE_ATOMICOPMGR_MACOS_FALSE@,$XERCES_USE_ATOMICOPMGR_MACOS_FALSE,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
 
